export const DUCKDUCKGO_SEARCH_TERM = "DUCKDUCKGO_SEARCH_TERM";
export const DUCKDUCKGO_SEARCH_REQUEST = "DUCKDUCKGO_SEARCH_REQUEST"
export const DUCKDUCKGO_SEARCH_SUCCESS = "DUCKDUCKGO_SEARCH_SUCCESS"
export const DUCKDUCKGO_SEARCH_FAILURE = "DUCKDUCKGO_SEARCH_FAILURE"
